{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "78fd4d45-8888-451e-969b-29cd72b81f8c",
   "metadata": {},
   "source": [
    "# Personal Expense Tracker with Visual Reports\n",
    "In this project, students will develop a simple Python application that helps users record, manage, and analyze their daily expenses. The system will allow users to add expenses, categorize them, view reports, and generate visual charts.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "388729c5-24ca-49fa-95e6-f0e8f41615a5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Loaded 14 old expenses.\n",
      "\n",
      "========================================\n",
      "       Personal Expense Tracker       \n",
      "========================================\n",
      "1. Add Expense\n",
      "2. View All Expenses\n",
      "3. Filter Expenses\n",
      "4. Generate Charts\n",
      "5. Export Expenses to CSV/Excel\n",
      "6. Exit\n",
      "7. Reset All Data (Delete Old Records)\n"
     ]
    }
   ],
   "source": [
    "import json\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# -------------------------------\n",
    "# Load existing expenses or start empty\n",
    "# -------------------------------\n",
    "try:\n",
    "    with open(\"expenses.json\", \"r\") as f:\n",
    "        expenses = json.load(f)\n",
    "except FileNotFoundError:\n",
    "    expenses = []\n",
    "\n",
    "print(f\"\\nLoaded {len(expenses)} old expenses.\")\n",
    "\n",
    "# -------------------------------\n",
    "# MAIN MENU LOOP\n",
    "# -------------------------------\n",
    "while True:\n",
    "    print(\"\\n\" + \"=\" * 40)\n",
    "    print(\"       Personal Expense Tracker       \")\n",
    "    print(\"=\" * 40)\n",
    "    print(\"1. Add Expense\")\n",
    "    print(\"2. View All Expenses\")\n",
    "    print(\"3. Filter Expenses\")\n",
    "    print(\"4. Generate Charts\")\n",
    "    print(\"5. Export Expenses to CSV/Excel\")\n",
    "    print(\"6. Exit\")\n",
    "    print(\"7. Reset All Data (Delete Old Records)\")\n",
    "\n",
    "    choice = input(\"Enter your choice (1-7): \")\n",
    "\n",
    "    # -------------------------------\n",
    "    # 1. Add Expense\n",
    "    # -------------------------------\n",
    "    if choice == \"1\":\n",
    "        expense = {}\n",
    "        amount = input(\"Enter Amount: \").strip()\n",
    "        date = input(\"Enter Date (YYYY-MM-DD): \").strip()\n",
    "        category = input(\"Enter Category (Food, Transport, etc.): \").strip().title()\n",
    "        note = input(\"Enter Note: \").strip().title()\n",
    "\n",
    "        expense[\"Amount\"] = amount\n",
    "        expense[\"Date\"] = date\n",
    "        expense[\"Category\"] = category\n",
    "        expense[\"Note\"] = note\n",
    "\n",
    "        expenses.append(expense)\n",
    "\n",
    "        with open(\"expenses.json\", \"w\") as f:\n",
    "            json.dump(expenses, f, indent=2)\n",
    "\n",
    "        print(\"\\nExpense added successfully!\")\n",
    "\n",
    "    # -------------------------------\n",
    "    # 2. View All Expenses\n",
    "    # -------------------------------\n",
    "    elif choice == \"2\":\n",
    "        if not expenses:\n",
    "            print(\"No expenses found.\")\n",
    "        else:\n",
    "            print(\"\\nAll Expenses:\\n\")\n",
    "            for e in expenses:\n",
    "                print(f\"Amount:   {e['Amount']}\")\n",
    "                print(f\"Date:     {e['Date']}\")\n",
    "                print(f\"Category: {e['Category']}\")\n",
    "                print(f\"Note:     {e['Note']}\")\n",
    "                print(\"-\" * 30)\n",
    "\n",
    "    # -------------------------------\n",
    "    # 3. Filter Expenses\n",
    "    # -------------------------------\n",
    "    elif choice == \"3\":\n",
    "        if not expenses:\n",
    "            print(\"No expenses found.\")\n",
    "        else:\n",
    "            print(\"Filter by:\\n1. Category\\n2. Date\")\n",
    "            filter_choice = input(\"Enter 1 or 2: \")\n",
    "\n",
    "            if filter_choice == \"1\":\n",
    "                cat = input(\"Enter category: \").strip().title()\n",
    "                filtered = [e for e in expenses if e[\"Category\"] == cat]\n",
    "\n",
    "            elif filter_choice == \"2\":\n",
    "                date = input(\"Enter date (YYYY-MM-DD): \").strip()\n",
    "                filtered = [e for e in expenses if e[\"Date\"] == date]\n",
    "\n",
    "            else:\n",
    "                print(\"Invalid choice.\")\n",
    "                filtered = []\n",
    "\n",
    "            if not filtered:\n",
    "                print(\"\\nNo matching expenses found.\")\n",
    "            else:\n",
    "                print(\"\\nFiltered Expenses:\\n\")\n",
    "                for e in filtered:\n",
    "                    print(f\"Amount:   {e['Amount']}\")\n",
    "                    print(f\"Date:     {e['Date']}\")\n",
    "                    print(f\"Category: {e['Category']}\")\n",
    "                    print(f\"Note:     {e['Note']}\")\n",
    "                    print(\"-\" * 30)\n",
    "\n",
    "    # -------------------------------\n",
    "    # 4. Generate Charts\n",
    "    # -------------------------------\n",
    "    elif choice == \"4\":\n",
    "        if not expenses:\n",
    "            print(\"No expenses to show in charts.\")\n",
    "        else:\n",
    "            df = pd.DataFrame(expenses)\n",
    "            df[\"Amount\"] = pd.to_numeric(df[\"Amount\"], errors=\"coerce\").fillna(0)\n",
    "            df[\"Date\"] = pd.to_datetime(df[\"Date\"], errors=\"coerce\")\n",
    "\n",
    "            # ===== Matplotlib Bar Chart =====\n",
    "            category_totals = df.groupby(\"Category\")[\"Amount\"].sum()\n",
    "            categories = category_totals.index\n",
    "            amounts = category_totals.values\n",
    "\n",
    "            plt.figure(figsize=(6, 4))\n",
    "            plt.bar(categories, amounts)\n",
    "            plt.title(\"Total Expenses by Category\")\n",
    "            plt.xlabel(\"Category\")\n",
    "            plt.ylabel(\"Amount\")\n",
    "            plt.xticks(rotation=45)\n",
    "            plt.tight_layout()\n",
    "            plt.savefig(\"bar_chart.png\")\n",
    "            plt.show()\n",
    "\n",
    "            # ===== Matplotlib Pie Chart =====\n",
    "            plt.figure(figsize=(6, 6))\n",
    "            plt.pie(amounts, labels=categories, autopct=\"%1.1f%%\", startangle=140)\n",
    "            plt.title(\"Expense Distribution by Category\")\n",
    "            plt.tight_layout()\n",
    "            plt.savefig(\"pie_chart.png\")\n",
    "            plt.show()\n",
    "\n",
    "            # ===== Plotly Monthly Trend =====\n",
    "            df[\"Month\"] = df[\"Date\"].dt.to_period(\"M\")\n",
    "            monthly_expense = df.groupby(\"Month\")[\"Amount\"].sum()\n",
    "\n",
    "            plt.figure(figsize=(10, 5))\n",
    "            monthly_expense.plot(marker=\"o\")\n",
    "            plt.title(\"Monthly Expense Trend\")\n",
    "            plt.xlabel(\"Month\")\n",
    "            plt.ylabel(\"Total Expenses\")\n",
    "            plt.grid(True)\n",
    "            plt.xticks(rotation=45)\n",
    "            plt.tight_layout()\n",
    "            plt.savefig(\"monthly_trend_line.png\")\n",
    "            plt.show()\n",
    "    # -------------------------------\n",
    "    # 5. Export to CSV/Excel\n",
    "    # -------------------------------\n",
    "    elif choice == \"5\":\n",
    "        if not expenses:\n",
    "            print(\"No expenses to export.\")\n",
    "        else:\n",
    "            df = pd.DataFrame(expenses)\n",
    "            df[\"Amount\"] = pd.to_numeric(df[\"Amount\"], errors=\"coerce\")\n",
    "            df[\"Date\"] = pd.to_datetime(df[\"Date\"], errors=\"coerce\").astype(str)\n",
    "\n",
    "            df.to_csv(\"expenses.csv\", index=False)\n",
    "            print(\"Expenses exported to expenses.csv successfully!\")\n",
    "\n",
    "    # -------------------------------\n",
    "    # 7. Reset All Data\n",
    "    # -------------------------------\n",
    "    elif choice == \"7\":\n",
    "        confirm = input(\"Are you sure you want to DELETE all records? (yes/no): \")\n",
    "        if confirm.lower() == \"yes\":\n",
    "            expenses = []\n",
    "            with open(\"expenses.json\", \"w\") as f:\n",
    "                json.dump([], f, indent=2)\n",
    "            empty_df = pd.DataFrame(columns=[\"Amount\", \"Date\", \"Category\", \"Note\"])\n",
    "            empty_df.to_csv(\"expenses.csv\", index=False)\n",
    "            print(\"\\nAll old data deleted successfully!\")\n",
    "        else:\n",
    "            print(\"Reset cancelled.\")\n",
    "\n",
    "    # -------------------------------\n",
    "    # 6. Exit\n",
    "    # -------------------------------\n",
    "    elif choice == \"6\":\n",
    "        print(\"Exiting program. Goodbye!\")\n",
    "        break\n",
    "\n",
    "    else:\n",
    "        print(\"Invalid choice, please try again.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e4451358-5a3b-4128-accd-7bd97e6d10b9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
